AWSTemplateFormatVersion: '2010-09-09'
Description: Create VPC, Subnet, EC2 Instance, Security Group, Internet Gateway, and Route Table

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/18
      EnableDnsSupport: true
      EnableDnsHostnames: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select  [ 0, !GetAZs '' ]
      CidrBlock: 10.0.0.0/19
  
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable SSH and HTTP access"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VPC       

  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0a3c3a20c09d6f377
      InstanceType: t2.micro
      KeyName: NV-privatekey
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref PublicSubnet1
          GroupSet:
            - !Ref SecurityGroup
          AssociatePublicIpAddress: true
      UserData: !Base64 |
        #!/bin/bash
        sudo -i 
        yum update all
        yum install httpd -y
        systemctl start httpd
        systemctl enable httpd
        echo "this instane made with the help of cft using jenkins pipeline" > /var/www/html/index.html
